/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  HasherSubset,
  HasherSubsetInterface,
} from "../../MerkleTreeSubset.sol/HasherSubset";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32[2]",
        name: "leftRight",
        type: "bytes32[2]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class HasherSubset__factory {
  static readonly abi = _abi;
  static createInterface(): HasherSubsetInterface {
    return new utils.Interface(_abi) as HasherSubsetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HasherSubset {
    return new Contract(address, _abi, signerOrProvider) as HasherSubset;
  }
}
